### ISSUE TITLE
Readability Support

### ISSUE THREAD

**Issue by encbladexp** [encbladexp/makeblog#17]
Readability is a real good online service with Kindle integration. We need to add some CSS Classes and Tags to our templates. => [Online Documentation](https://www.readability.com/developers/guidelines)

**Comment by KopfKrieg** [comment]
FYI: The Readability service shut down on September 30, 2016: [The Readability bookmarking service will shut down on September 30, 2016.](https://medium.com/@readability/the-readability-bookmarking-service-will-shut-down-on-september-30-2016-1641cc18e02b)

**Comment by encbladexp** [comment]
Yes, we should focus on improved "Read Mode" of modern Browsers instead.
